sockets:
  host: localhost
  port: 9092
  cron:
    getVehicles: "0/30 * * * * *"
adapter:
  host: "https://apidev.meep.me/tripplan/api/v1/routers/"
  vehicles:
    lisboa: "/lisboa/resources"
    params:
      lowerLeftLatLon: "38.711046,-9.160096"
      upperRightLatLon: "38.739429,-9.137115"
      companyZoneIds: "545,467,473"